<?php echo $this->plugin('doctype') ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <?php echo $this->plugin('headLink')->appendStylesheet('/css/global.css') ?>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>ZF Quickstart Application</b>
    </div>
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->plugin('url')->direct(
            array('controller'=>'guestbook'),
            array('name' => 'default')) ?>">Guestbook</a>
    </div>
</div>

<?php echo $this->vars()->getRawValue('content') ?>

</body>
</html>
