<?php echo $this->broker('doctype') ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <?php echo $this->broker('headLink')->appendStylesheet('/css/global.css') ?>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>ZF Quickstart Application</b>
    </div>
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->broker('url')->direct(
            array('controller'=>'guestbook', 'action' => 'index'),
            array('name' => 'default')) ?>">Guestbook</a>
    </div>
</div>

<?php 
    $vars = $this->vars();
    // Forcing a container here so we can escape in subviews
    echo $this->render($vars['content_script'], new \Zend\View\Variables($vars['content']));
?>

</body>
</html>
